var outMessages=[
    "Are you kidding? Even a one year old kitten can crack your password. Try longer passwords that contains upper/lower case letters, numbers and symbols.",
    "Okay your password looks random enough. But it’s still too short. I can crack this password over lunch time.",
    "How many words are there with 3 letters? Not much, really, and your password is one of them. It’s very predictable.",
    "It seems like you know how to make a random password. But you also should know that computers are fast and can try every possible password with this length in a matter of seconds.",
    "How predictable can you be? Don’t choose cliché passwords. I can assure you that someone else have used this password before.",
    "It seems like you know how to make a random password. But you also should know that computers are fast and can try every possible password with this length in a matter of minutes.",
    "So you think no one else thought of this password before? Just because you added some randomness doesn’t mean it’s secure enough.",
    "It seems like you know how to make a random password. But you also should know that computers are fast and can try every possible password with this length in a matter of hours.",
    "You are doing good job with mixing random characters. But somewhere in there, I found an English word. That’s going to make cracking the password easier for wicked cats with hacking skills.",
    "I like the length of this password. But the length of my tail didn’t help me much. If I were you I would make my password more secure.",
    "That is one long password that someone else thought of before.",
    "Good job. This password is good enough to keep you secure. Unless you are the President.",
    "You are trying to use common English words, or some password that someone have used before. Do you think it’s wise?",
    "Good job. This password has an adequate length and enough randomness. Make sure you don’t forget it",
    "You are trying to use common English words, or some password that someone have used before. Do you think it’s wise?",
    "That is one long random password. But it needs more types of characters. If you are serious about your security.",
    "You think you are smart by inserting random characters between words? Words are easy to guess, they are found in a dictionary! Try more random letters.",
    "Good password I must say. It can be made even better by adding different types of characters!",
    "Separating words by numbers or symbols is a good strategy. But it’s better to separate the words themselves. Cut wo#r2ds by numbers or symbols!",
    "Excellent password! I’m proud of you human.",
    "Separating words by numbers or symbols is a good strategy. But it’s better to separate the words themselves. Inject your words with numbers or symbols.",
    "This is a super long random password. But evil cat hackers with super-fast computers have nothing better but to wait for your password to get cracked, even if it took those days. Add more types of characters to make it impossible to crack.",
    "Long sentence with words separated by numbers or symbols. This is considered secure if we have an English dictionary with unlimited words. But I have a dictionary and it’s only 1000 pages. I can try all these words to figure out your password or part of it",
    "SUPER SECURE. Now that’s how one should make a password. Amazing job human!",
    "Long sentence with words separated by numbers or symbols. This is considered secure if we have an English dictionary with unlimited words. But I have a dictionary and it’s only 1000 pages. I can try all these words to figure out your password or part of it."
];